# Generated by Django 3.0.8 on 2020-07-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Start')),
                ('end_at', models.DateTimeField(verbose_name='End')),
                ('eventname', models.CharField(max_length=30, verbose_name='Eventname')),
            ],
        ),
    ]
