# Generated by Django 3.0.2 on 2020-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Authority'),
        ),
    ]
