# Generated by Django 3.0.8 on 2020-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200505_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authority',
            field=models.IntegerField(default=0, verbose_name='authority'),
        ),
    ]
