# Generated by Django 3.0.2 on 2020-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20200309_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남'), ('F', '여')], default='M', max_length=2, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='admission_year',
            field=models.IntegerField(choices=[(2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020')], verbose_name='Admission_year'),
        ),
    ]
