# Generated by Django 3.1.1 on 2021-01-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20200912_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_year',
            field=models.IntegerField(blank=True, choices=[(2014, '2014 (1기)'), (2015, '2015 (2기)'), (2016, '2016 (3기)'), (2017, '2017 (4기)'), (2018, '2018 (5기)'), (2019, '2019 (6기)'), (2020, '2020 (7기)'), (2021, '2021 (8기)'), (2014, '교직원')], null=True, verbose_name='Admission_year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Is superuser'),
        ),
    ]
