# Generated by Django 3.0.2 on 2020-04-14 08:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Pub_date')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('num_view', models.IntegerField(default=0, verbose_name='Num_view')),
                ('num_comment', models.IntegerField(default=0, verbose_name='Num_comment')),
                ('num_good', models.IntegerField(default=0, verbose_name='Num_good')),
                ('num_bad', models.IntegerField(default=0, verbose_name='Num_bad')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='File_1')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='File_2')),
                ('file_3', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='File_3')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='Content')),
                ('authority', models.IntegerField(default=0, verbose_name='Authority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
    ]
