# Generated by Django 3.0.2 on 2020-03-18 08:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Pub_date')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('num_view', models.IntegerField(default=0, verbose_name='Num_view')),
                ('num_comment', models.IntegerField(default=0, verbose_name='Num_comment')),
                ('num_good', models.IntegerField(default=0, verbose_name='Num_good')),
                ('num_bad', models.IntegerField(default=0, verbose_name='Num_bad')),
                ('file_1', models.ImageField(blank=True, null=True, upload_to='file/%Y/%m/%d', verbose_name='File_1')),
                ('file_2', models.ImageField(blank=True, null=True, upload_to='file/%Y/%m/%d', verbose_name='File_1')),
                ('file_3', models.ImageField(blank=True, null=True, upload_to='file/%Y/%m/%d', verbose_name='File_1')),
            ],
        ),
    ]
