# Generated by Django 3.0.2 on 2020-03-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_pub_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_1',
            field=models.ImageField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='File_1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_2',
            field=models.ImageField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='File_1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_3',
            field=models.ImageField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='File_1'),
        ),
    ]
