# Generated by Django 3.0.2 on 2020-05-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200501_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='num_bad',
        ),
        migrations.RemoveField(
            model_name='article',
            name='num_comment',
        ),
        migrations.RemoveField(
            model_name='article',
            name='num_good',
        ),
    ]
