# Generated by Django 3.0.2 on 2020-03-18 09:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200318_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='File_1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='File_1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='File_1'),
        ),
    ]
