# Generated by Django 3.1.1 on 2021-01-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200505_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_popup',
            field=models.BooleanField(default=False, verbose_name='팝업창으로 띄우는 게시글'),
        ),
    ]
