# Generated by Django 3.0.2 on 2020-03-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=20, verbose_name='Menu_name')),
                ('menu_url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('page_authority', models.IntegerField(default=0, verbose_name='page_authority')),
                ('unit', models.BooleanField(verbose_name='unit')),
            ],
        ),
    ]
