# Generated by Django 3.0.8 on 2020-09-11 16:43

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='board',
            name='represent_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
